// Generates dist/ from src/. Uses only Node built-ins: run `npm run build`.
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const dist = join(root, 'dist');

const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';
const optional = (p) => (existsSync(p) ? read(p) : '');

const components = JSON.parse(readFileSync(join(src, 'components', 'index.json'), 'utf8')).map((c) => {
  const dir = join(src, 'components', c.slug);
  return { ...c, html: read(join(dir, 'component.html')), css: read(join(dir, 'component.css')), js: optional(join(dir, 'component.js')) };
});
const base = read(join(src, 'tokens', 'fb-base.css'));

rmSync(dist, { recursive: true, force: true });
mkdirSync(join(dist, 'snippets'), { recursive: true });

const banner = '/* Funding Bay component library. Generated by scripts/build.mjs: edit src/, not this file. */\n';
writeFileSync(join(dist, 'fb.css'), banner + [base, ...components.map((c) => c.css)].join('\n'));
writeFileSync(join(dist, 'fb.js'), banner + components.filter((c) => c.js).map((c) => `/* ${c.name} */\n${c.js}`).join('\n'));

const snippet = (c) => c.html + (c.js ? `<script>\n${c.js}</script>\n` : '');
for (const c of components) writeFileSync(join(dist, 'snippets', `${c.slug}.html`), snippet(c));

const filler = '<p>Placeholder article paragraph so you can see how the component sits between sections of the real post.</p>\n';
writeFileSync(join(dist, 'preview.html'), `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Funding Bay components preview</title>
<link href="https://fonts.googleapis.com/css2?family=Hind+Madurai:wght@500;600;700&family=Lato:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="fb.css">
<style>
body{font-family:Lato,sans-serif;color:#212529;line-height:1.75;font-size:17px;margin:0}
.w{max-width:780px;margin:0 auto;padding:2rem 1.5rem 5rem}
h1,h2{font-family:"Hind Madurai",sans-serif;font-weight:800;color:#11323F;line-height:1.3}h2{margin:3rem 0 1rem}
a{color:#D9472B}
</style></head><body><div class="w">
<h1>Funding Bay components preview</h1>
${components.map((c) => `<h2>${c.name}</h2>\n${filler}${c.html}`).join('\n')}${filler.repeat(6)}</div>
<script src="fb.js"></script>
</body></html>
`);

console.log(`Built ${components.length} components into dist/`);
