// Generates dist/ and the gallery pages from src/. Uses only Node built-ins: run `npm run build`.
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const dist = join(root, 'dist');
const gallery = join(root, 'gallery');

const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trimEnd() + '\n';
const optional = (p) => (existsSync(p) ? read(p) : '');
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const components = JSON.parse(readFileSync(join(src, 'components', 'index.json'), 'utf8')).map((c) => {
  const dir = join(src, 'components', c.slug);
  return {
    ...c,
    html: read(join(dir, 'component.html')),
    css: read(join(dir, 'component.css')),
    js: optional(join(dir, 'component.js')),
    readme: optional(join(dir, 'README.md')),
  };
});
const base = read(join(src, 'tokens', 'fb-base.css'));
const snippet = (c) => c.html + (c.js ? `<script>\n${c.js}</script>\n` : '');

// dist/
rmSync(dist, { recursive: true, force: true });
mkdirSync(join(dist, 'snippets'), { recursive: true });

const banner = '/* Funding Bay component library. Generated by scripts/build.mjs: edit src/, not this file. */\n';
writeFileSync(join(dist, 'fb.css'), banner + [base, ...components.map((c) => c.css)].join('\n'));
writeFileSync(join(dist, 'fb.js'), banner + components.filter((c) => c.js).map((c) => `/* ${c.name} */\n${c.js}`).join('\n'));
for (const c of components) writeFileSync(join(dist, 'snippets', `${c.slug}.html`), snippet(c));

const fonts = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?family=Hind+Madurai:wght@500;600;700;800&family=Lato:wght@400;700&display=swap" rel="stylesheet">';
const articleStyle = `<style>
body{font-family:Lato,sans-serif;color:#212529;line-height:1.75;font-size:17px;margin:0;background:#fff}
.w{max-width:780px;margin:0 auto;padding:2rem 1.5rem 5rem}
h1,h2{font-family:"Hind Madurai",sans-serif;font-weight:800;color:#11323F;line-height:1.3}h2{margin:3rem 0 1rem}
a{color:#D9472B}
</style>`;
const filler = '<p>Placeholder article paragraph so you can see how the component sits between sections of the real post.</p>\n';

writeFileSync(join(dist, 'preview.html'), `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Funding Bay components preview</title>
${fonts}
<link rel="stylesheet" href="fb.css">
${articleStyle}</head><body><div class="w">
<h1>Funding Bay components preview</h1>
${components.map((c) => `<h2>${c.name}</h2>\n${filler}${c.html}`).join('\n')}${filler.repeat(6)}</div>
<script src="fb.js"></script>
</body></html>
`);

// gallery/ (gallery.css and gallery.js are hand-written; everything else here is generated)
for (const entry of readdirSync(gallery, { withFileTypes: true })) {
  if (entry.isDirectory() || entry.name === 'index.html') rmSync(join(gallery, entry.name), { recursive: true, force: true });
}

function markdown(md) {
  const inline = (s) => esc(s)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  const out = [];
  let list = false;
  for (const line of md.split('\n')) {
    if (/^# /.test(line)) continue;
    const item = line.match(/^- (.*)/);
    if (item) { if (!list) { out.push('<ul>'); list = true; } out.push(`<li>${inline(item[1])}</li>`); continue; }
    if (list) { out.push('</ul>'); list = false; }
    if (line.trim()) out.push(`<p>${inline(line)}</p>`);
  }
  if (list) out.push('</ul>');
  return out.join('\n');
}

const tags = (c) => [c.js ? 'Interactive' : 'HTML and CSS only', c.once ? 'Once per post' : null]
  .filter(Boolean).map((t) => `<span class="g-tag">${t}</span>`).join('');

const page = (title, rel, body) => `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<meta name="robots" content="noindex">
${fonts}
<link rel="stylesheet" href="${rel}../dist/fb.css">
<link rel="stylesheet" href="${rel}gallery.css">
</head><body>
<a class="g-skip" href="#main">Skip to content</a>
<header class="g-head"><div class="g-head-in">
  <a class="g-brand" href="${rel}">Funding Bay <span>components</span></a>
  <nav class="g-nav" aria-label="Library"><a href="${rel}">All components</a><a href="${rel}../dist/preview.html">One-page preview</a><a href="${rel}../dist/fb.css">fb.css</a><a href="${rel}../dist/fb.js">fb.js</a></nav>
</div></header>
<main class="g-main" id="main">
${body}
</main>
<footer class="g-foot">Internal component library for fundingbay.co.uk blog posts. Demo content is illustrative only.</footer>
<script src="${rel}gallery.js"></script>
</body></html>
`;

writeFileSync(join(gallery, 'index.html'), page('Funding Bay component library', '', `<h1>Blog component library</h1>
<p class="g-lead">Interactive tools and infographics for Funding Bay blog posts. Open a component to see a live demo, copy its HTML and CSS, and read where it goes in a post.</p>
<ul class="g-grid">
${components.map((c) => `  <li><a class="g-card" href="${c.slug}/"><h2>${esc(c.name)}</h2><p>${esc(c.summary || '')}</p><div class="g-tags">${tags(c)}</div></a></li>`).join('\n')}
</ul>`));

for (const c of components) {
  const dir = join(gallery, c.slug);
  mkdirSync(dir, { recursive: true });

  const demoBody = c.once
    ? `<h1>${esc(c.name)} demo</h1>\n${filler}${c.html}${filler.repeat(30)}`
    : `${filler}${c.html}${filler}`;
  writeFileSync(join(dir, 'demo.html'), `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(c.name)} demo</title>
<meta name="robots" content="noindex">
${fonts}
<link rel="stylesheet" href="../../dist/fb.css">
${articleStyle}</head><body><div class="w">
${demoBody}</div>
${c.js ? `<script>\n${c.js}</script>\n` : ''}${c.once ? '' : `<script>
(function(){if(window.parent===window)return;function send(){parent.postMessage({fbDemoHeight:document.documentElement.scrollHeight},'*')}
if(window.ResizeObserver)new ResizeObserver(send).observe(document.body);window.addEventListener('load',send);send()})();
</script>
`}</body></html>
`);

  const css = `${base}\n${c.css}`;
  const code = (id, label, text) => `<details class="g-code"><summary>${label}</summary><pre id="${id}"><code>${esc(text)}</code></pre></details>`;
  writeFileSync(join(dir, 'index.html'), page(`${c.name} | Funding Bay components`, '../', `<a class="g-back" href="../">← All components</a>
<h1>${esc(c.name)}</h1>
<p class="g-lead">${esc(c.summary || '')}</p>
<div class="g-tags" style="margin-bottom:1.4rem">${tags(c)}</div>

<section class="g-panel" aria-labelledby="demo-h">
  <h2 id="demo-h" style="margin-top:0">Live demo</h2>
  <div class="g-toolbar">
    <div class="g-seg" role="group" aria-label="Demo width">
      <button type="button" data-g-width="full" aria-pressed="true">Desktop</button>
      <button type="button" data-g-width="375" aria-pressed="false">Mobile 375px</button>
    </div>
    <div class="g-actions">
      <button type="button" class="fb-btn" data-g-copy="code-html" data-g-label="HTML">Copy HTML</button>
      <button type="button" class="fb-btn fb-btn--ghost" data-g-copy="code-css" data-g-label="CSS">Copy CSS</button>
    </div>
  </div>
  <p class="g-status" data-g-status aria-live="polite"></p>
  <div class="g-frame-wrap"><iframe class="g-frame" data-g-frame${c.once ? '' : ' data-g-autoheight'} src="demo.html" title="${esc(c.name)} live demo" loading="lazy"></iframe></div>
  ${c.once ? '<p style="font-size:.88rem;margin:.6rem 0 0">Scroll inside the demo to see it in action.</p>' : ''}
</section>

<section class="g-notes" aria-labelledby="use-h">
  <h2 id="use-h">How to use it</h2>
  <p><strong>Copy HTML</strong> gives you the markup and its script, ready for a WordPress Custom HTML block. Swap the demo text for the post's own.
  <strong>Copy CSS</strong> gives the shared base styles plus this component's styles. If <code>fb.css</code> is already in Additional CSS, you only need the HTML.</p>
  ${markdown(c.readme)}
</section>

<section aria-labelledby="code-h">
  <h2 id="code-h">Code</h2>
  ${code('code-html', 'HTML (paste into a Custom HTML block)', snippet(c))}
  ${code('code-css', 'CSS (base styles plus this component)', css)}
</section>`));
}

writeFileSync(join(root, 'index.html'), `<!DOCTYPE html><html lang="en-GB"><head><meta charset="UTF-8">
<title>Funding Bay component library</title>
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=gallery/">
</head><body><p><a href="gallery/">Open the Funding Bay component library</a></p></body></html>
`);

console.log(`Built ${components.length} components into dist/ and gallery/`);
